"use strict";
var assert = require("assert");
var fs = require("fs");
var path = require("path");
var root = path.resolve(__dirname, "..");
var workflow = fs.readFileSync(path.join(root, ".github", "workflows", "release-windows.yml"), "utf8");
var installer = fs.readFileSync(path.join(root, "tools", "installer", "SIRK-Portal.iss"), "utf8");
var service = fs.readFileSync(path.join(root, "tools", "installer", "Install-SIRK-Portal-Service.ps1"), "utf8");
var updater = fs.readFileSync(path.join(root, "tools", "installer", "Ensure-SirkUpdater.ps1"), "utf8");
assert.ok(workflow.indexOf("SIRK Portal Windows Release") >= 0);
assert.ok(workflow.indexOf("actions/upload-artifact@v4") >= 0);
assert.ok(workflow.indexOf("gh release upload") >= 0);
assert.ok(workflow.indexOf("WinSW SHA-256 verification failed") >= 0);
assert.ok(workflow.indexOf("$global:LASTEXITCODE = 0") >= 0);
assert.ok(workflow.indexOf("test scripts assets") < 0);
assert.ok(workflow.indexOf("node-version: \"24\"") >= 0);
assert.ok(installer.indexOf("OutputBaseFilename=SIRK-Portal-{#AppVersion}-Windows-x64-Setup") >= 0);
assert.ok(installer.indexOf("PrepareToInstall") >= 0);
assert.ok(service.indexOf("$env:ProgramData\\SIRK\\Portal") >= 0);
assert.ok(service.indexOf("$serviceId = 'SirkPortal'") >= 0);
assert.ok(service.indexOf("'SirkPortalStandalone'") >= 0);
assert.ok(service.indexOf("'sirkportal.exe'") >= 0);
assert.ok(service.indexOf("SIRK_PORTAL_FQDN") >= 0);
assert.ok(service.indexOf("SIRK_PUBLIC_URL") >= 0);
assert.ok(service.indexOf("agent-enrollment-token.txt") >= 0);
assert.ok(service.indexOf("portal.pfx") >= 0);
assert.ok(service.indexOf("Ensure-SirkUpdater.ps1") >= 0);
assert.ok(updater.indexOf("install-release.ps1") >= 0);
assert.ok(updater.indexOf("applicationId       = 'sirk-portal'") >= 0);
assert.ok(updater.indexOf("SIRK_PORTAL_SHARED_UPDATER_READY") >= 0);
console.log("SIRK Portal Windows installer workflow: OK");
