"use strict";
var assert = require("assert");
var fs = require("fs");
var path = require("path");
var root = path.resolve(__dirname, "..");
function read(file) { return fs.readFileSync(path.join(root, file), "utf8"); }
var portal = read("public/portal/standalone/index.html");
var workspace = read("public/portal/standalone/scripts/device-workspace.js").replace(/\r\n/g, "\n");
assert(portal.indexOf('select.value="3"') >= 0);
assert(portal.indexOf('select.value="2"') >= 0);
assert(portal.indexOf("Zapytaj o zgodę + Bar") >= 0);
assert(portal.indexOf("Zapytaj o zgodę") >= 0);
assert(portal.indexOf("Pasek Prywatności") >= 0);
assert(portal.indexOf("Number(amt.state)===2") >= 0);
assert(portal.indexOf("pendingConsent") >= 0);
assert(workspace.indexOf('"/api/agent-desktop/frame?tenantId="') >= 0);
assert(workspace.indexOf('response.blob()') >= 0);
assert(workspace.indexOf('X-SIRK-Sequence') >= 0);
assert(workspace.indexOf('desktop.snapshot') < 0);
assert(workspace.indexOf('fetch("/api/agent-desktop/input"') >= 0);
assert(workspace.indexOf('runAgentOperation(node, "desktop.sessions"') >= 0);
assert(workspace.indexOf('runAgentOperation(node, "desktop.monitors"') >= 0);
assert(workspace.indexOf('action: "clipboardGet"') >= 0);
assert(workspace.indexOf('action: "clipboardSet"') >= 0);
assert(workspace.indexOf('action: "clipboardFileSet"') >= 0);
assert(workspace.indexOf("navigator.clipboard.readText()") >= 0);
assert(workspace.indexOf("navigator.clipboard.writeText") >= 0);
assert(workspace.indexOf('image.addEventListener("drop"') >= 0);
assert(workspace.indexOf('key: "C", modifiers: "Control"') >= 0);
assert(workspace.indexOf('key: "V", modifiers: "Control"') >= 0);
assert(workspace.indexOf("function desktopData(value)") >= 0);
assert(workspace.indexOf("desktopData(value).text") >= 0);
assert(workspace.indexOf('action: "text"') >= 0);
assert(workspace.indexOf('action: "leftDown"') >= 0);
assert(workspace.indexOf('action: "leftUp"') >= 0);
assert(workspace.indexOf('action: "move"') >= 0);
assert(workspace.indexOf('action: "wheel"') >= 0);
assert(workspace.indexOf('action: "middleClick"') >= 0);
assert(workspace.indexOf('"desktop.admin.start"') >= 0);
assert(workspace.indexOf("data-agent-desktop-connect") >= 0);
assert(workspace.indexOf("data-agent-desktop-disconnect") >= 0);
assert(workspace.indexOf("PowerShell SYSTEM") >= 0);
assert(workspace.indexOf("streamGeneration") >= 0);
assert(workspace.indexOf("waitMilliseconds: 25000") >= 0);
assert(workspace.indexOf("setTimeout(poll, 0)") >= 0);
assert(workspace.indexOf('value="auto"') >= 0);
assert(workspace.indexOf('value="minimum"') >= 0);
assert(workspace.indexOf("function effectiveProfile()") >= 0);
assert(workspace.indexOf('"&after=" + encodeURIComponent(snapshot.sequence || 0)') >= 0);
assert(workspace.indexOf('"&waitMilliseconds=25000"') >= 0);
assert(workspace.indexOf("data-agent-desktop-stats") >= 0);
assert(workspace.indexOf("data-stat-latency") >= 0);
assert(workspace.indexOf("setTimeout(function () { snapshot(generation); }, 0)") >= 0);
assert(workspace.indexOf('return fetch(endpoint, {\n            method: "POST",') >= 0);
console.log("Portal allowAll save and Desktop connection controls: OK");
