"use strict";
var assert=require("assert"),fs=require("fs"),path=require("path");
var root=path.join(__dirname,"..");
var server=fs.readFileSync(path.join(root,"plugin-main-standalone.js"),"utf8");
var app=fs.readFileSync(path.join(root,"public/portal/standalone/scripts/app.js"),"utf8");
var required=["shared-ui/toolbar-config.js","shared-ui/toolbar-api.js","shared-ui/toolbar.js","shared-ui/tabs.js","shared-ui/layout.js","shared-ui/settings.js","shared-ui/status-nav.js","shared-ui/page.js","shared-ui/tree.js","shared-ui/catalog.js","shared-ui/results.js","shared-ui/result-layout.js","shared-ui/script-tools.js","shared-ui/script-definition-form.js","shared-ui/confirm-execution-form.js","shared-ui/script-edit-actions.js","shared-ui/system-credentials-form.js","module-shell.js","approvalcenter.js","moverequests.js","mycommands.js","myjira.js","defendertools.js","portal-management.js","portal-subfolder-icons.js","portal-folder-collapse.js","vendor/sirk-portal/portal-ui-contract.js"];
required.forEach(function(asset){assert.ok(server.indexOf(JSON.stringify(asset)+":")>=0,"Missing standalone asset route: "+asset);});
assert.ok(app.indexOf("pin\", \"SIRKPortal")>=0||app.indexOf("pin", "SIRKPortal")>=0,"Settings and runtime URLs must use SIRKPortal");
assert.ok(app.indexOf("pin=SirkPlatform")<0,"Legacy pin must not remain in standalone app");
assert.ok(fs.existsSync(path.join(root,"public/portal/vendor/portal-ui-contract.js")),"Portal contract JS must exist");
console.log("Standalone Portal complete asset manifest: OK");
