using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace Sirk.Portal.Ui;

internal static class PortalAssetBundler
{
    private const string Switch = "--bundle-assets";

    private static readonly BundleDefinition[] Bundles =
    [
        new(
            "portal-shell.bundle.js",
            [
                "portal/standalone/scripts/core.js",
                "portal/standalone/scripts/app.js",
                "portal/standalone/scripts/view-mode.js"
            ]),
        new(
            "portal-devices.bundle.js",
            [
                "portal/standalone/scripts/central-tunnel-transport.js",
                "portal/standalone/scripts/central-desktop-longpoll.js",
                "portal/standalone/scripts/quick-commands-api-compat.js",
                "portal/standalone/scripts/device-workspace.js",
                "portal/standalone/scripts/device-tabs.js",
                "portal/standalone/scripts/workspace-connection.js",
                "portal/standalone/scripts/device-tabs-lifecycle-v4.js",
                "portal/standalone/scripts/device-tab-selection-state.js",
                "portal/standalone/scripts/header-toggle-context-menu.js",
                "portal/standalone/scripts/terminal-connect.js"
            ]),
        new(
            "portal-modules.bundle.js",
            [
                "shared/ui/toolbar-config.js",
                "shared/ui/toolbar-api.js",
                "shared/ui/toolbar.js",
                "shared/ui/tabs.js",
                "shared/ui/layout.js",
                "shared/ui/settings.js",
                "shared/ui/status-nav.js",
                "shared/ui/page.js",
                "shared/ui/tree.js",
                "shared/ui/catalog.js",
                "shared/ui/results.js",
                "shared/ui/result-layout.js",
                "shared/ui/script-tools.js",
                "shared/ui/script-definition-form.js",
                "shared/ui/confirm-execution-form.js",
                "shared/ui/script-edit-actions.js",
                "shared/ui/system-credentials-form.js",
                "shared/module-shell.js",
                "portal/icons.js",
                "modules/approvals/index.js",
                "modules/move-requests/index.js",
                "modules/commands/index.js",
                "modules/jira/index.js",
                "modules/security/index.js",
                "portal/management.js",
                "portal/subfolder-icons.js",
                "portal/folder-collapse.js",
                "portal/vendor/portal-ui-contract.js",
                "portal/vendor/settings-structure.js",
                "portal/standalone/scripts/cleanup.js",
                "portal/system-updates.js",
                "portal/standalone/scripts/maintenance-update-restart-guard.js",
                "portal/standalone/scripts/settings-native-v2.js",
                "portal/standalone/scripts/update-availability-ui.js",
                "shared/icon-registry.js",
                "portal/standalone/scripts/navigation.js"
            ])
    ];

    public static bool IsRequested(string[] args) =>
        args.Length > 0 && string.Equals(args[0], Switch, StringComparison.Ordinal);

    public static async Task<int> RunAsync(string[] args)
    {
        if (args.Length != 3)
        {
            Console.Error.WriteLine($"Usage: {Switch} <public-source> <bundle-output>");
            return 64;
        }

        try
        {
            await BuildAsync(args[1], args[2]);
            return 0;
        }
        catch (Exception exception) when (
            exception is IOException or UnauthorizedAccessException or InvalidDataException)
        {
            Console.Error.WriteLine(exception.Message);
            return 1;
        }
    }

    private static async Task BuildAsync(string sourceRoot, string outputRoot)
    {
        var source = Path.GetFullPath(sourceRoot);
        var output = Path.GetFullPath(outputRoot);
        if (!Directory.Exists(source))
            throw new InvalidDataException($"Portal public source does not exist: {source}");

        Directory.CreateDirectory(output);
        var manifest = new List<object>();
        foreach (var bundle in Bundles)
        {
            var builder = new StringBuilder(256 * 1024);
            builder.AppendLine("/* Generated by SIRK Portal .NET 10 AssetBundler. Do not edit. */");
            foreach (var relative in bundle.Sources)
            {
                var path = Path.GetFullPath(Path.Combine(
                    source,
                    relative.Replace('/', Path.DirectorySeparatorChar)));
                if (!path.StartsWith(source + Path.DirectorySeparatorChar, StringComparison.Ordinal) ||
                    !File.Exists(path))
                {
                    throw new InvalidDataException(
                        $"Bundle source is missing or outside public root: {relative}");
                }

                builder.AppendLine();
                builder.Append("/* source: ").Append(relative).AppendLine(" */");
                builder.Append((await File.ReadAllTextAsync(path, Encoding.UTF8)).TrimEnd());
                builder.AppendLine();
                builder.AppendLine(";");
            }

            var content = builder.ToString();
            var target = Path.Combine(output, bundle.Name);
            await File.WriteAllTextAsync(target, content, new UTF8Encoding(false));
            var hash = Convert.ToHexString(
                SHA256.HashData(Encoding.UTF8.GetBytes(content))).ToLowerInvariant();
            manifest.Add(new
            {
                bundle = bundle.Name,
                sha256 = hash,
                sources = bundle.Sources.Length
            });
        }

        await File.WriteAllTextAsync(
            Path.Combine(output, "portal-bundles.json"),
            JsonSerializer.Serialize(
                manifest,
                new JsonSerializerOptions { WriteIndented = true }),
            new UTF8Encoding(false));
    }

    private sealed record BundleDefinition(string Name, string[] Sources);
}
