from pathlib import Path

path = Path(__file__).resolve().parents[2] / "src/Sirk.Portal/Sirk.Portal.csproj"
text = path.read_text(encoding="utf-8")
old = '''  <PropertyGroup>\n    <PortalPublicSource>$(MSBuildProjectDirectory)/../../public</PortalPublicSource>\n  </PropertyGroup>\n\n  <Target Name="GeneratePortalBuildBundles"\n          AfterTargets="Build"\n          Condition="'$(DesignTimeBuild)' != 'true'">\n    <Exec Command="dotnet &quot;$(TargetPath)&quot; --bundle-assets &quot;$(PortalPublicSource)&quot; &quot;$(TargetDir)public/assets/bundles&quot;" />\n  </Target>\n\n  <Target Name="GeneratePortalPublishBundles" AfterTargets="Publish">\n    <Exec Command="dotnet &quot;$(PublishDir)$(AssemblyName).dll&quot; --bundle-assets &quot;$(PortalPublicSource)&quot; &quot;$(PublishDir)public/assets/bundles&quot;" />\n  </Target>\n'''
new = '''  <PropertyGroup>\n    <PortalPublicSource>$(MSBuildProjectDirectory)/../../public</PortalPublicSource>\n    <PortalBundleHostDll>$(MSBuildProjectDirectory)/bin/$(Configuration)/$(TargetFramework)/$(AssemblyName).dll</PortalBundleHostDll>\n  </PropertyGroup>\n\n  <Target Name="GeneratePortalBuildBundles"\n          AfterTargets="Build"\n          Condition="'$(DesignTimeBuild)' != 'true' and '$(SkipPortalBundleGeneration)' != 'true' and '$(RuntimeIdentifier)' == ''">\n    <Exec Command="dotnet &quot;$(TargetPath)&quot; --bundle-assets &quot;$(PortalPublicSource)&quot; &quot;$(TargetDir)public/assets/bundles&quot;" />\n  </Target>\n\n  <Target Name="PreparePortalPublishBundleHost"\n          BeforeTargets="GeneratePortalPublishBundles"\n          Condition="'$(RuntimeIdentifier)' != ''">\n    <MSBuild Projects="$(MSBuildProjectFullPath)"\n             Targets="Build"\n             Properties="Configuration=$(Configuration);TargetFramework=$(TargetFramework);RuntimeIdentifier=;SelfContained=false;PublishReadyToRun=false;SkipPortalBundleGeneration=true" />\n  </Target>\n\n  <Target Name="GeneratePortalPublishBundles" AfterTargets="Publish">\n    <Exec Command="dotnet &quot;$(PortalBundleHostDll)&quot; --bundle-assets &quot;$(PortalPublicSource)&quot; &quot;$(PublishDir)public/assets/bundles&quot;" />\n  </Target>\n'''
if old not in text:
    if "PreparePortalPublishBundleHost" in text:
        raise SystemExit(0)
    raise SystemExit("bundle target block not found")
path.write_text(text.replace(old, new, 1), encoding="utf-8", newline="\n")
