from pathlib import Path
import textwrap


def replace_once(path: Path, old: str, new: str) -> None:
    value = path.read_text(encoding="utf-8")
    count = value.count(old)
    if count != 1:
        raise SystemExit(f"{path}: expected one match, found {count}")
    path.write_text(value.replace(old, new, 1), encoding="utf-8", newline="\n")


bundler = r'''
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace Sirk.Portal.Ui;

internal static class PortalAssetBundler
{
    private const string Switch = "--bundle-assets";

    private static readonly BundleDefinition[] Bundles =
    [
        new(
            "portal-shell.bundle.js",
            [
                "portal/standalone/scripts/core.js",
                "portal/standalone/scripts/app.js",
                "portal/standalone/scripts/view-mode.js"
            ]),
        new(
            "portal-devices.bundle.js",
            [
                "modules/commands/index.js",
                "portal/standalone/scripts/device-workspace.js",
                "portal/standalone/scripts/device-tabs.js",
                "portal/standalone/scripts/terminal-connect.js"
            ]),
        new(
            "portal-modules.bundle.js",
            [
                "shared/ui/toolbar-config.js",
                "shared/ui/toolbar-api.js",
                "shared/ui/toolbar.js",
                "shared/ui/tabs.js",
                "shared/ui/layout.js",
                "shared/ui/settings.js",
                "shared/ui/status-nav.js",
                "shared/ui/page.js",
                "shared/ui/tree.js",
                "shared/ui/catalog.js",
                "shared/ui/results.js",
                "shared/ui/result-layout.js",
                "shared/ui/script-tools.js",
                "shared/ui/script-definition-form.js",
                "shared/ui/confirm-execution-form.js",
                "shared/ui/script-edit-actions.js",
                "shared/ui/system-credentials-form.js",
                "shared/module-shell.js",
                "portal/icons.js",
                "modules/approvals/index.js",
                "modules/move-requests/index.js",
                "modules/commands/index.js",
                "modules/jira/index.js",
                "modules/security/index.js",
                "portal/management.js",
                "portal/subfolder-icons.js",
                "portal/folder-collapse.js",
                "portal/vendor/portal-ui-contract.js",
                "portal/vendor/settings-structure.js",
                "portal/standalone/scripts/cleanup.js",
                "portal/system-updates.js",
                "portal/standalone/scripts/settings-native-v2.js",
                "shared/icon-registry.js",
                "portal/standalone/scripts/navigation.js"
            ])
    ];

    public static bool IsRequested(string[] args) =>
        args.Length > 0 && string.Equals(args[0], Switch, StringComparison.Ordinal);

    public static async Task<int> RunAsync(string[] args)
    {
        if (args.Length != 3)
        {
            Console.Error.WriteLine($"Usage: {Switch} <public-source> <bundle-output>");
            return 64;
        }

        try
        {
            await BuildAsync(args[1], args[2]);
            return 0;
        }
        catch (Exception exception) when (
            exception is IOException or UnauthorizedAccessException or InvalidDataException)
        {
            Console.Error.WriteLine(exception.Message);
            return 1;
        }
    }

    private static async Task BuildAsync(string sourceRoot, string outputRoot)
    {
        var source = Path.GetFullPath(sourceRoot);
        var output = Path.GetFullPath(outputRoot);
        if (!Directory.Exists(source))
            throw new InvalidDataException($"Portal public source does not exist: {source}");

        Directory.CreateDirectory(output);
        var manifest = new List<object>();
        foreach (var bundle in Bundles)
        {
            var builder = new StringBuilder(256 * 1024);
            builder.AppendLine("/* Generated by SIRK Portal .NET 10 AssetBundler. Do not edit. */");
            foreach (var relative in bundle.Sources)
            {
                var path = Path.GetFullPath(Path.Combine(
                    source,
                    relative.Replace('/', Path.DirectorySeparatorChar)));
                if (!path.StartsWith(source + Path.DirectorySeparatorChar, StringComparison.Ordinal) ||
                    !File.Exists(path))
                {
                    throw new InvalidDataException(
                        $"Bundle source is missing or outside public root: {relative}");
                }

                builder.AppendLine();
                builder.Append("/* source: ").Append(relative).AppendLine(" */");
                builder.Append((await File.ReadAllTextAsync(path, Encoding.UTF8)).TrimEnd());
                builder.AppendLine();
                builder.AppendLine(";");
            }

            var content = builder.ToString();
            var target = Path.Combine(output, bundle.Name);
            await File.WriteAllTextAsync(target, content, new UTF8Encoding(false));
            var hash = Convert.ToHexString(
                SHA256.HashData(Encoding.UTF8.GetBytes(content))).ToLowerInvariant();
            manifest.Add(new
            {
                bundle = bundle.Name,
                sha256 = hash,
                sources = bundle.Sources.Length
            });
        }

        await File.WriteAllTextAsync(
            Path.Combine(output, "portal-bundles.json"),
            JsonSerializer.Serialize(
                manifest,
                new JsonSerializerOptions { WriteIndented = true }),
            new UTF8Encoding(false));
    }

    private sealed record BundleDefinition(string Name, string[] Sources);
}
'''
Path("src/Sirk.Portal/Ui/PortalAssetBundler.cs").write_text(
    textwrap.dedent(bundler).lstrip(), encoding="utf-8", newline="\n")

program = Path("src/Sirk.Portal/Program.cs")
replace_once(
    program,
    """if (RuntimeHealthProbe.IsRequested(args))
{
    Environment.ExitCode = await RuntimeHealthProbe.RunAsync(args);
    return;
}

var builder = WebApplication.CreateBuilder""",
    """if (RuntimeHealthProbe.IsRequested(args))
{
    Environment.ExitCode = await RuntimeHealthProbe.RunAsync(args);
    return;
}

if (PortalAssetBundler.IsRequested(args))
{
    Environment.ExitCode = await PortalAssetBundler.RunAsync(args);
    return;
}

var builder = WebApplication.CreateBuilder""")

project = Path("src/Sirk.Portal/Sirk.Portal.csproj")
replace_once(
    project,
    "</Project>\n",
    """  <PropertyGroup>
    <PortalPublicSource>$(MSBuildProjectDirectory)/../../public</PortalPublicSource>
  </PropertyGroup>

  <Target Name="GeneratePortalBuildBundles"
          AfterTargets="Build"
          Condition="'$(DesignTimeBuild)' != 'true'">
    <Exec Command="dotnet &quot;$(TargetPath)&quot; --bundle-assets &quot;$(PortalPublicSource)&quot; &quot;$(TargetDir)public/assets/bundles&quot;" />
  </Target>

  <Target Name="GeneratePortalPublishBundles" AfterTargets="Publish">
    <Exec Command="dotnet &quot;$(PublishDir)$(AssemblyName).dll&quot; --bundle-assets &quot;$(PortalPublicSource)&quot; &quot;$(PublishDir)public/assets/bundles&quot;" />
  </Target>
</Project>
""")

endpoints = Path("src/Sirk.Portal/Ui/PortalUiEndpoints.cs")
replace_once(
    endpoints,
    """            [\"standalone-core.js\"] = \"portal/standalone/scripts/core.js\",
            [\"portal-standalone.js\"] = \"portal/standalone/scripts/app.js\",""",
    """            [\"standalone-core.js\"] = \"portal/standalone/scripts/core.js\",
            [\"bundles/portal-shell.bundle.js\"] = \"assets/bundles/portal-shell.bundle.js\",
            [\"bundles/portal-devices.bundle.js\"] = \"assets/bundles/portal-devices.bundle.js\",
            [\"bundles/portal-modules.bundle.js\"] = \"assets/bundles/portal-modules.bundle.js\",
            [\"bundles/portal-bundles.json\"] = \"assets/bundles/portal-bundles.json\",
            [\"portal-standalone.js\"] = \"portal/standalone/scripts/app.js\",""")

index = Path("public/portal/standalone/index.html")
replace_once(
    index,
    """  <script src=\"__ASSET_BASE__/standalone-core.js?v=__VERSION__\"></script>
  <script src=\"__ASSET_BASE__/portal-standalone.js?v=__VERSION__\"></script>
  <script src=\"__ASSET_BASE__/portal-device-workspace.js?v=__VERSION__\"></script>
  <script src=\"__ASSET_BASE__/portal-device-tabs.js?v=__VERSION__\"></script>""",
    """  <script src=\"__ASSET_BASE__/bundles/portal-shell.bundle.js?v=__VERSION__\"></script>""")
replace_once(
    index,
    """  <script src=\"__ASSET_BASE__/portal-view-mode.js?v=__VERSION__\"></script>
  <script src=\"__ASSET_BASE__/portal-standalone-nav.js?v=__VERSION__\"></script>""",
    """  <!-- Devices and administration modules are loaded lazily by portal-shell.bundle.js. -->""")

app = Path("public/portal/standalone/scripts/app.js")
replace_once(
    app,
    """    var deviceSearch = \"\";
    var deviceFilter = \"all\";
""",
    """    var deviceSearch = \"\";
    var deviceFilter = \"all\";
    var bundlePromises = Object.create(null);
""")
replace_once(
    app,
    """    var VIEW_KEYS = [\"overview\", \"devices\", \"approvals\", \"automation\", \"monitoring\", \"assets\", \"management\", \"reports\", \"security\", \"settings\"];
""",
    """    var VIEW_KEYS = [\"overview\", \"devices\", \"approvals\", \"automation\", \"monitoring\", \"assets\", \"management\", \"reports\", \"security\", \"settings\"];
    var VIEW_BUNDLES = {
        devices: \"devices\",
        approvals: \"modules\",
        assets: \"modules\",
        management: \"modules\",
        security: \"modules\",
        settings: \"modules\"
    };
""")
replace_once(
    app,
    """    function load(id, name) { return core.loadScript(id, asset(name)); }
    function moduleState(key) { return bootstrap && bootstrap.modules && bootstrap.modules[key] || null; }
""",
    """    function load(id, name) { return core.loadScript(id, asset(name)); }
    function loadBundle(name) {
        if (!name) return Promise.resolve();
        if (!bundlePromises[name]) {
            bundlePromises[name] = load(
                \"sirk-portal-bundle-\" + name,
                \"bundles/portal-\" + name + \".bundle.js\");
        }
        return bundlePromises[name];
    }
    function ensureViewBundle(view) { return loadBundle(VIEW_BUNDLES[view]); }
    function moduleState(key) { return bootstrap && bootstrap.modules && bootstrap.modules[key] || null; }
""")

old_render = """    function render(view) {
        view = VIEW_KEYS.indexOf(view) >= 0 && viewEnabled(view) ? view : firstEnabledView();
        activeView = view;
        var sequence = ++renderSequence;
        applyViewSurface(view);
        applyShellLanguage();
        title.textContent = viewName(view);
        Array.prototype.forEach.call(document.querySelectorAll(\".sirk-standalone-nav [data-view]\"), function (button) {
            var active = button.getAttribute(\"data-view\") === view;
            button.classList.toggle(\"is-active\", active);
            button.setAttribute(\"aria-current\", active ? \"page\" : \"false\");
        });
        if (view === \"overview\") overview(sequence);
        else if (view === \"management\") management(sequence);
        else if (view === \"approvals\") approvals(sequence);
        else if (view === \"settings\") settings();
        else if (view === \"devices\") devices(sequence, false);
        else if (view === \"automation\") automation(sequence);
        else if (moduleViews[view]) mountModule(view, moduleViews[view], sequence);
        else if (view === \"monitoring\") placeholder(view, t(\"monitoringPlaceholder\"));
        else if (view === \"reports\") placeholder(view, t(\"reportsPlaceholder\"));
        else placeholder(view, t(\"genericPlaceholder\"));
        if (window.location.hash !== \"#\" + view) history.replaceState(null, \"\", \"#\" + view);
    }
"""
new_render = """    function renderLoaded(view, sequence) {
        if (!isCurrent(sequence)) return;
        if (view === \"overview\") overview(sequence);
        else if (view === \"management\") management(sequence);
        else if (view === \"approvals\") approvals(sequence);
        else if (view === \"settings\") settings();
        else if (view === \"devices\") devices(sequence, false);
        else if (view === \"automation\") automation(sequence);
        else if (moduleViews[view]) mountModule(view, moduleViews[view], sequence);
        else if (view === \"monitoring\") placeholder(view, t(\"monitoringPlaceholder\"));
        else if (view === \"reports\") placeholder(view, t(\"reportsPlaceholder\"));
        else placeholder(view, t(\"genericPlaceholder\"));
        if (window.location.hash !== \"#\" + view) history.replaceState(null, \"\", \"#\" + view);
    }

    function render(view) {
        view = VIEW_KEYS.indexOf(view) >= 0 && viewEnabled(view) ? view : firstEnabledView();
        activeView = view;
        var sequence = ++renderSequence;
        applyViewSurface(view);
        applyShellLanguage();
        title.textContent = viewName(view);
        Array.prototype.forEach.call(document.querySelectorAll(\".sirk-standalone-nav [data-view]\"), function (button) {
            var active = button.getAttribute(\"data-view\") === view;
            button.classList.toggle(\"is-active\", active);
            button.setAttribute(\"aria-current\", active ? \"page\" : \"false\");
        });
        if (VIEW_BUNDLES[view]) loading(t(\"loadingModules\"));
        ensureViewBundle(view).then(function () {
            renderLoaded(view, sequence);
        }).catch(function (reason) {
            if (isCurrent(sequence)) {
                showError(
                    viewName(view) + \": \" + t(\"loadFailed\"),
                    reason && (reason.stack || reason.message) || reason);
            }
        });
    }
"""
replace_once(app, old_render, new_render)

value = app.read_text(encoding="utf-8")
start = value.find("    function loadDependencies() {")
end = value.find("    function start() {", start)
if start < 0 or end < 0:
    raise SystemExit("app.js: loadDependencies block not found")
value = value[:start] + value[end:]
old_start = """            applyUserProfile();
            applyShellLanguage();
            return loadDependencies();
        }).then(function () {"""
new_start = """            applyUserProfile();
            applyShellLanguage();
        }).then(function () {"""
if value.count(old_start) != 1:
    raise SystemExit("app.js: eager start chain not found")
value = value.replace(old_start, new_start, 1)
if "loadDependencies" in value:
    raise SystemExit("app.js: legacy eager loader remains")
app.write_text(value, encoding="utf-8", newline="\n")

navigation = Path("public/portal/standalone/scripts/navigation.js")
replace_once(
    navigation,
    """    function loadUiContract() {
        loadStyle(\"sirk-platform-portal-ui-contract-style\", \"vendor/sirk-portal/portal-ui-contract.css\");
        loadStyle(\"sirk-platform-portal-cleanup-style\", \"portal-cleanup.css\");
        loadScript(\"sirk-platform-portal-ui-contract-script\", \"vendor/sirk-portal/portal-ui-contract.js\");
        loadScript(\"sirk-platform-portal-cleanup-script\", \"portal-cleanup.js\");
    }
""",
    """    function loadUiContract() {
        loadStyle(\"sirk-platform-portal-ui-contract-style\", \"vendor/sirk-portal/portal-ui-contract.css\");
        loadStyle(\"sirk-platform-portal-cleanup-style\", \"portal-cleanup.css\");
    }
""")
replace_once(
    navigation,
    """    loadUiContract();
    loadStyle(\"sirk-platform-system-updates-style\", \"system-updates.css\");
    loadStyle(\"sirk-platform-settings-style\", \"settings.css\");
    loadScript(\"sirk-platform-system-updates-script\", \"system-updates.js\");
    loadScript(\"sirk-platform-settings-script\", \"settings.js\");
    loadScript(\"sirk-platform-icon-registry\", \"shared/icon-registry.js\", replacePortalIcons);
    observeDeviceWorkspace();
    loadScript(\"sirk-platform-portal-terminal-connect\", \"portal-terminal-connect.js\");
""",
    """    loadUiContract();
    loadStyle(\"sirk-platform-system-updates-style\", \"system-updates.css\");
    loadStyle(\"sirk-platform-settings-style\", \"settings.css\");
    replacePortalIcons();
    observeDeviceWorkspace();
""")

print("SIRK Portal .NET lazy bundle migration applied.")
